# Generated by Django 5.0.14 on 2026-09-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Fixed IP Camera', 'Fixed IP Camera'), ('PTZ Camera', 'PTZ Camera'), ('360-Degree Camera', '360-Degree Camera')], default='Fixed IP Camera', max_length=50)),
                ('resolution', models.CharField(default='1920 × 1080', max_length=20)),
                ('threshold', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('danger', 'Danger'), ('offline', 'Offline')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='CameraPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'camera_persons',
            },
        ),
        migrations.CreateModel(
            name='MonthlyCrowd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=5)),
                ('count', models.IntegerField(default=0)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'monthly_crowd',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(default='🔔', max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('unread', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('control', models.CharField(default='full', max_length=50)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CrowdRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_records', to='DatabaseConectivity.camera')),
            ],
            options={
                'db_table': 'crowd_records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
